name: Build Mandarin WOTD JSON

on:
  schedule:
    # Runs daily at 00:05 Europe/London (i.e., 23:05 UTC or 00:05 UTC depending on DST)
    - cron: "5 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # HSK CSVs (chinese,pinyin,english) — we’ll combine all levels:
      HSK_URLS: >
        https://raw.githubusercontent.com/plaktos/hsk_csv/master/hsk1.csv
        https://raw.githubusercontent.com/plaktos/hsk_csv/master/hsk2.csv
        https://raw.githubusercontent.com/plaktos/hsk_csv/master/hsk3.csv
        https://raw.githubusercontent.com/plaktos/hsk_csv/master/hsk4.csv
        https://raw.githubusercontent.com/plaktos/hsk_csv/master/hsk5.csv
        https://raw.githubusercontent.com/plaktos/hsk_csv/master/hsk6.csv
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build today.json
        run: |
          python tools/build_wotd.py

      - name: Debug workspace
        run: |
          echo "PWD=$(pwd)"
          echo "Branch ref: ${{ github.ref }}"
          echo "Branch name: ${{ github.ref_name }}"
          ls -la

      - name: Commit and push today.json
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          git config --global safe.directory '*'
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Make sure we’re on the right branch (esp. for workflow_dispatch / schedule)
          git checkout "$BRANCH_NAME"

          # Show the file we expect
          ls -la today.json || true
          echo "git status before:"
          git status --porcelain

          # Stage & commit if changed or new
          git add -A
          if git diff --cached --quiet; then
            echo "No staged changes (today.json may match current)."
          else
            git commit -m "Update today.json (WOTD)"
          fi

          # Push (won’t error if nothing to push)
          git push origin "$BRANCH_NAME" || true

          echo "git status after:"
          git status --porcelain

